from sqlalchemy import text

from src.database.sql_alchemy import connect

# This SQL script first drops all existing tables to ensure a clean slate,
# then recreates them. This is useful for development and testing to reset the database schema.
sql_query="""
---
--- Delete tables
---
-- The CASCADE option automatically drops any objects that depend on the tables (like foreign keys).
DROP TABLE 
    "WORK", 
    "BANK", 
    "PERSON_ADDRESS", 
    "PERSON", 
    "ADDRESS" 
CASCADE;


---
--- PERSON TABLE
--- ID is set to auto-increment
---
CREATE TABLE "PERSON"(
   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "passport" VARCHAR(255) NOT NULL,
   "name" VARCHAR(255) NOT NULL,
   "last_name" VARCHAR(255) NOT NULL,
   "sex" VARCHAR(255) NOT NULL,
   "email" VARCHAR(255) NOT NULL,
   "phone" VARCHAR(255) NOT NULL
);

---
--- ADDRESS TABLE
--- ID is set to auto-increment
---
CREATE TABLE "ADDRESS"(
   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "street_name" VARCHAR(255) NOT NULL,
   "city" VARCHAR(255) NOT NULL,
   "ip_address" VARCHAR(255) NOT NULL
);

---
--- PERSON_ADDRESS TABLE (Junction Table)
--- We use a COMPOSITE primary key made up of the two foreign keys
--- This table creates a many-to-many relationship between PERSON and ADDRESS.
---
CREATE TABLE "PERSON_ADDRESS"(
   "address_id" BIGINT NOT NULL,
   "person_id" BIGINT NOT NULL,
   "type" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("address_id", "person_id") -- Composite Primary Key
);

---
--- BANK TABLE
--- ID is set to auto-increment
---
CREATE TABLE "BANK"(
   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "person_id" BIGINT NOT NULL,
   "iban" VARCHAR NOT NULL,
   "salary" VARCHAR NOT NULL
);

---
--- WORK TABLE
--- ID is set to auto-increment
---
CREATE TABLE "WORK"(
   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "person_id" BIGINT NOT NULL,
   "company" VARCHAR(255) NOT NULL,
   "position" VARCHAR(255) NOT NULL,
   "phone" VARCHAR(255) NOT NULL,
   "email" VARCHAR(255) NOT NULL
);

---
--- Foreign Key Definitions (Relations)
--- These constraints enforce referential integrity between the tables.
---

ALTER TABLE
   "WORK" ADD CONSTRAINT "work_person_id_foreign" FOREIGN KEY("person_id") REFERENCES "PERSON"("id");
ALTER TABLE
   "BANK" ADD CONSTRAINT "bank_person_id_foreign" FOREIGN KEY("person_id") REFERENCES "PERSON"("id");
ALTER TABLE
   "PERSON_ADDRESS" ADD CONSTRAINT "person_address_address_id_foreign" FOREIGN KEY("address_id") REFERENCES "ADDRESS"("id");
ALTER TABLE
   "PERSON_ADDRESS" ADD CONSTRAINT "person_address_person_id_foreign" FOREIGN KEY("person_id") REFERENCES "PERSON"("id");
"""

# --- Main execution block ---

# Prompt the user for confirmation because this is a destructive operation.
print("This will recreate the database. All data in the database will be lost!!!")
cmd = input("Do you which to continue? (y/n) ")

# Only proceed if the user explicitly agrees.
if cmd.lower() == "y":
    session = connect()
    if session is not None:
        try:
            # Execute the raw SQL query within a transaction.
            session.execute(text(sql_query))
            session.commit()
            print("\n✅ Database has been successfully cleaned and recreated.")
        except Exception as e:
            # If any error occurs, roll back the transaction to leave the database in a consistent state.
            session.rollback()
            print(f"❌ Error executing raw SQL in session: {e}")
else:
    print("\nAborted by user.")